/**
 * @file test_dynarray.c
 * @brief Test suite for dynamic array implementation
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This file contains comprehensive tests for the DynArray data structure,
 * including creation, manipulation, and type-safe operations.
 */

#include <stdio.h>
#include <stdlib.h>
#include "../../utils/dynarray.h"

/**
 * @brief Test function for dynamic array functionality
 *
 * Tests all major operations: creation, push_back, get, set, resize, pop_back, clear, destroy.
 */
void test_dynarray(void) {
    printf("Testing DynArray with type-safe macros\n");

    // Test create with type macro
    DynArray *arr = DYNARRAY_CREATE(int);
    if (!arr) {
        printf("Failed to create array\n");
        return;
    }
    printf("Created array, size: %zu, capacity: %zu\n", dynarray_size(arr), dynarray_capacity(arr));

    // Test push_back with type-specific macro
    int values[] = {10, 20, 30, 40, 50};
    for (int i = 0; i < 5; ++i) {
        DYNARRAY_PUSH_BACK_INT(arr, values[i]);
    }
    printf("After push_back 5 elements, size: %zu, capacity: %zu\n", dynarray_size(arr), dynarray_capacity(arr));

    // Test get with type macro
    printf("Testing DYNARRAY_GET:\n");
    for (size_t i = 0; i < dynarray_size(arr); ++i) {
        int *val = DYNARRAY_GET(arr, int, i);
        if (val) {
            printf("Element at %zu: %d\n", i, *val);
        } else {
            printf("Failed to get element at %zu\n", i);
        }
    }

    // Test const get
    printf("Testing DYNARRAY_CONST_GET:\n");
    for (size_t i = 0; i < dynarray_size(arr); ++i) {
        const int *val = DYNARRAY_CONST_GET(arr, int, i);
        if (val) {
            printf("Const element at %zu: %d\n", i, *val);
        } else {
            printf("Failed to const get element at %zu\n", i);
        }
    }

    // Test set with type macro (using generic set for now)
    int new_val = 100;
    if (dynarray_set(arr, 2, &new_val) == 0) {
        printf("Set element at 2 to %d\n", new_val);
        int *val = DYNARRAY_GET(arr, int, 2);
        if (val) {
            printf("Element at 2 after set: %d\n", *val);
        }
    } else {
        printf("Failed to set element at 2\n");
    }

    // Test resize
    if (dynarray_resize(arr, 10, &new_val) == 0) {
        printf("Resized to 10, size: %zu, capacity: %zu\n", dynarray_size(arr), dynarray_capacity(arr));
        for (size_t i = 5; i < 10; ++i) {
            int *val = DYNARRAY_GET(arr, int, i);
            if (val) {
                printf("Element at %zu after resize: %d\n", i, *val);
            }
        }
    } else {
        printf("Failed to resize\n");
    }

    // Test pop_back
    int popped;
    if (dynarray_pop_back(arr, &popped) == 0) {
        printf("Popped: %d, size now: %zu\n", popped, dynarray_size(arr));
    } else {
        printf("Failed to pop_back\n");
    }

    // Test clear
    dynarray_clear(arr);
    printf("After clear, size: %zu, capacity: %zu\n", dynarray_size(arr), dynarray_capacity(arr));

    // Test destroy
    dynarray_destroy(arr);
    printf("Destroyed array\n");

    printf("All tests completed\n");
}