/**
 * @file test_stack.c
 * @brief Test suite for type-safe stack implementation
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This file contains comprehensive tests for the Stack data structure,
 * including type safety, capacity management, and all operations.
 */

#include <stdio.h>
#include <stdlib.h>
#include "../../utils/stack.h"

/**
 * @brief Test function for stack functionality
 *
 * Tests all major operations: creation, push, pop, top, type checking, etc.
 */
void test_stack(void) {
    printf("Testing Type-Safe Stack\n");

    // Test create with type macro
    Stack *int_stack = stack_create(sizeof(int), STACK_TYPE_INT);
    if (!int_stack) {
        printf("Failed to create int stack\n");
        return;
    }
    printf("Created int stack, size: %zu, capacity: %zu, type: %d\n",
           stack_size(int_stack), stack_capacity(int_stack), stack_get_type(int_stack));

    // Test push with type macro
    printf("Pushing elements: ");
    for (int i = 1; i <= 5; ++i) {
        int val = i * 10;
        stack_push(int_stack, &val, STACK_TYPE_INT);
        printf("%d ", val);
    }
    printf("\n");
    printf("After push, size: %zu, capacity: %zu\n", stack_size(int_stack), stack_capacity(int_stack));

    // Test top
    int top_val;
    if (stack_top(int_stack, &top_val) == 0) {
        printf("Top element: %d\n", top_val);
    } else {
        printf("Failed to get top element\n");
    }

    // Test type mismatch (should fail)
    printf("Testing type mismatch (pushing double to int stack):\n");
    double double_val = 3.14;
    if (stack_push(int_stack, &double_val, STACK_TYPE_DOUBLE) != 0) {
        printf("✓ Correctly rejected type mismatch\n");
    } else {
        printf("✗ Failed to detect type mismatch\n");
    }

    // Test pop
    printf("Popping elements:\n");
    while (!stack_is_empty(int_stack)) {
        int popped;
        if (stack_pop(int_stack, &popped) == 0) {
            printf("Popped: %d, size now: %zu\n", popped, stack_size(int_stack));
        } else {
            printf("Failed to pop\n");
            break;
        }
    }

    // Test capacity shrinkage
    printf("Capacity after emptying: %zu\n", stack_capacity(int_stack));

    // Test clear
    // First refill the stack
    for (int i = 1; i <= 3; ++i) {
        int val = i * 100;
        stack_push(int_stack, &val, STACK_TYPE_INT);
    }
    printf("After refilling, size: %zu\n", stack_size(int_stack));

    stack_clear(int_stack);
    printf("After clear, size: %zu, capacity: %zu\n", stack_size(int_stack), stack_capacity(int_stack));

    // Test destroy
    stack_destroy(int_stack);
    printf("Destroyed int stack\n");

    // Test different types
    printf("\nTesting double stack:\n");
    Stack *double_stack = stack_create(sizeof(double), STACK_TYPE_DOUBLE);
    double d1 = 1.1, d2 = 2.2;
    stack_push(double_stack, &d1, STACK_TYPE_DOUBLE);
    stack_push(double_stack, &d2, STACK_TYPE_DOUBLE);

    double d_top;
    if (stack_top(double_stack, &d_top) == 0) {
        printf("Double stack top: %.2f\n", d_top);
    }

    stack_destroy(double_stack);
    printf("Destroyed double stack\n");

    printf("All stack tests completed\n");
}