/**
 * @file test_queue.c
 * @brief Unit tests and examples for queue implementations
 * @author Generated by AI Assistant
 * @date 2026-05-13
 *
 * This test file covers both array-backed and linked-list-backed queues.
 */

#include <stdio.h>
#include <stdlib.h>
#include "../utils/queue_array.h"
#include "../utils/queue_list.h"

static void print_array_queue_example(void)
{
    printf("--- Array Queue Example ---\n");

    QueueArray *queue = QUEUE_ARRAY_CREATE(int);
    if (!queue) {
        printf("Failed to create array queue\n");
        return;
    }

    for (int i = 1; i <= 5; ++i) {
        int result = queue_array_enqueue(queue, &i, QUEUE_TYPE_INT);
        if (result != QUEUE_ARRAY_OK) {
            printf("enqueue error: %s\n", queue_array_error_string(result));
            break;
        }
    }

    int front_value = 0;
    QUEUE_ARRAY_FRONT(queue, int, &front_value);
    printf("Front value: %d\n", front_value);

    int back_value = 0;
    QUEUE_ARRAY_BACK(queue, int, &back_value);
    printf("Back value: %d\n", back_value);

    while (!queue_array_is_empty(queue)) {
        int value = 0;
        queue_array_dequeue(queue, &value);
        printf("Dequeued %d, size now %zu\n", value, queue_array_size(queue));
    }

    queue_array_destroy(queue);
}

static void print_list_queue_example(void)
{
    printf("--- List Queue Example ---\n");

    QueueList *queue = QUEUE_LIST_CREATE(int);
    if (!queue) {
        printf("Failed to create list queue\n");
        return;
    }

    for (int i = 10; i <= 50; i += 10) {
        int result = queue_list_enqueue(queue, &i, QUEUE_TYPE_INT);
        if (result != QUEUE_LIST_OK) {
            printf("enqueue error: %s\n", queue_list_error_string(result));
            break;
        }
    }

    int front_value = 0;
    QUEUE_LIST_FRONT(queue, int, &front_value);
    printf("Front value: %d\n", front_value);

    int back_value = 0;
    QUEUE_LIST_BACK(queue, int, &back_value);
    printf("Back value: %d\n", back_value);

    while (!queue_list_is_empty(queue)) {
        int value = 0;
        queue_list_dequeue(queue, &value);
        printf("Dequeued %d, size now %zu\n", value, queue_list_size(queue));
    }

    queue_list_destroy(queue);
}

static void test_type_mismatch(void)
{
    printf("--- Queue Type Safety Test ---\n");
    QueueArray *queue = QUEUE_ARRAY_CREATE(int);
    int int_value = 123;
    double double_value = 3.14;

    queue_array_enqueue(queue, &int_value, QUEUE_TYPE_INT);
    int result = queue_array_enqueue(queue, &double_value, QUEUE_TYPE_DOUBLE);
    if (result == QUEUE_ARRAY_ERROR_TYPE_MISMATCH) {
        printf("Correctly rejected type mismatch for array queue\n");
    }

    queue_array_destroy(queue);
}

static void test_clone_operations(void)
{
    printf("--- Queue Clone Test ---\n");
    QueueArray *source = QUEUE_ARRAY_CREATE(int);
    for (int i = 1; i <= 3; ++i) {
        queue_array_enqueue(source, &i, QUEUE_TYPE_INT);
    }

    QueueArray *deep = queue_array_clone_deep(source);
    QueueArray *shallow = queue_array_clone_shallow(source);
    if (deep && shallow) {
        int a, b;
        queue_array_front(deep, &a);
        queue_array_front(shallow, &b);
        printf("Deep front %d, shallow front %d\n", a, b);
    }

    queue_array_destroy(deep);
    queue_array_destroy(source);
    queue_array_destroy(shallow);
}

void test_queue(void)
{
    printf("=== Queue Unit Tests ===\n");
    print_array_queue_example();
    print_list_queue_example();
    test_type_mismatch();
    test_clone_operations();
    printf("=== Queue tests completed ===\n");
}
