/**
 * @file dynarray.c
 * @brief Dynamic array implementation source file
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This file contains the implementation of the dynamic array functions.
 * It provides automatic memory management and type-agnostic storage.
 */

#include "dynarray.h"
#include <stdlib.h>
#include <string.h>

/**
 * @brief Internal function to grow the array capacity
 * @param arr Pointer to the DynArray
 * @param min_capacity Minimum required capacity
 * @return 0 on success, -1 on failure
 */
static int dynarray_grow(DynArray *arr, size_t min_capacity)
{
    size_t new_capacity = arr->capacity ? arr->capacity * 2 : 4;
    if (new_capacity < min_capacity) {
        new_capacity = min_capacity;
    }

    void *new_data = realloc(arr->data, new_capacity * arr->elem_size);
    if (!new_data) {
        return -1;
    }

    arr->data = new_data;
    arr->capacity = new_capacity;
    return 0;
}

DynArray *dynarray_create(size_t elem_size)
{
    return dynarray_create_typed(elem_size, DYNARRAY_TYPE_UNKNOWN);
}

DynArray *dynarray_create_with_capacity(size_t elem_size, size_t capacity)
{
    return dynarray_create_with_capacity_typed(elem_size, capacity, DYNARRAY_TYPE_UNKNOWN);
}

DynArray *dynarray_create_typed(size_t elem_size, int type_id)
{
    return dynarray_create_with_capacity_typed(elem_size, 0, type_id);
}

DynArray *dynarray_create_with_capacity_typed(size_t elem_size, size_t capacity, int type_id)
{
    if (elem_size == 0) {
        return NULL;
    }

    DynArray *arr = (DynArray *)malloc(sizeof(DynArray));
    if (!arr) {
        return NULL;
    }

    arr->data = NULL;
    arr->size = 0;
    arr->capacity = 0;
    arr->elem_size = elem_size;
    arr->type_id = type_id;

    if (capacity > 0) {
        if (dynarray_reserve(arr, capacity) != 0) {
            free(arr);
            return NULL;
        }
    }

    return arr;
}

void dynarray_destroy(DynArray *arr)
{
    if (!arr) {
        return;
    }
    free(arr->data);
    free(arr);
}

int dynarray_reserve(DynArray *arr, size_t min_capacity)
{
    if (!arr) {
        return -1;
    }
    if (min_capacity <= arr->capacity) {
        return 0;
    }
    return dynarray_grow(arr, min_capacity);
}

int dynarray_resize(DynArray *arr, size_t new_size, const void *default_value)
{
    if (!arr) {
        return -1;
    }
    if (new_size > arr->capacity) {
        if (dynarray_grow(arr, new_size) != 0) {
            return -1;
        }
    }

    if (new_size > arr->size && default_value != NULL) {
        size_t count = new_size - arr->size;
        void *start = (char *)arr->data + arr->size * arr->elem_size;
        for (size_t i = 0; i < count; ++i) {
            memcpy((char *)start + i * arr->elem_size, default_value, arr->elem_size);
        }
    }

    arr->size = new_size;
    return 0;
}

int dynarray_push_back(DynArray *arr, const void *item)
{
    if (!arr || !item) {
        return -1;
    }
    if (arr->size >= arr->capacity) {
        if (dynarray_grow(arr, arr->size + 1) != 0) {
            return -1;
        }
    }

    memcpy((char *)arr->data + arr->size * arr->elem_size, item, arr->elem_size);
    arr->size += 1;
    return 0;
}

int dynarray_pop_back(DynArray *arr, void *out_item)
{
    if (!arr || arr->size == 0) {
        return -1;
    }
    arr->size -= 1;
    if (out_item != NULL) {
        memcpy(out_item, (char *)arr->data + arr->size * arr->elem_size, arr->elem_size);
    }
    return 0;
}

void *dynarray_get(DynArray *arr, size_t index)
{
    if (!arr || index >= arr->size) {
        return NULL;
    }
    return (char *)arr->data + index * arr->elem_size;
}

const void *dynarray_const_get(const DynArray *arr, size_t index)
{
    if (!arr || index >= arr->size) {
        return NULL;
    }
    return (const char *)arr->data + index * arr->elem_size;
}

int dynarray_set(DynArray *arr, size_t index, const void *item)
{
    if (!arr || !item || index >= arr->size) {
        return -1;
    }
    memcpy((char *)arr->data + index * arr->elem_size, item, arr->elem_size);
    return 0;
}

void dynarray_clear(DynArray *arr)
{
    if (!arr) {
        return;
    }
    arr->size = 0;
}

size_t dynarray_size(const DynArray *arr)
{
    return arr ? arr->size : 0;
}

size_t dynarray_capacity(const DynArray *arr)
{
    return arr ? arr->capacity : 0;
}

int dynarray_get_type(const DynArray *arr)
{
    return arr ? arr->type_id : DYNARRAY_TYPE_UNKNOWN;
}
