/**
 * @file queue_list.h
 * @brief Linked list queue implementation for generic data types
 * @author Generated by AI Assistant
 * @date 2026-05-13
 *
 * This file provides a list-backed queue implementation supporting fixed
 * capacity, runtime type checking, and deep clone semantics. The linked list
 * queue is naturally dynamic and can also be used as a circular queue in
 * logical order.
 *
 * Time complexity:
 *   enqueue: O(1)
 *   dequeue: O(1)
 *   front/back: O(1)
 *   size/isEmpty/isFull/capacity: O(1)
 *   clear: O(n)
 *   clone_deep: O(n)
 */

#ifndef QUEUE_LIST_H
#define QUEUE_LIST_H

#include <stdbool.h>
#include <stddef.h>

#ifdef QUEUE_THREAD_SAFE
#include <pthread.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define QUEUE_LIST_OK 0
#define QUEUE_LIST_ERROR -1
#define QUEUE_LIST_ERROR_EMPTY -2
#define QUEUE_LIST_ERROR_FULL -3
#define QUEUE_LIST_ERROR_TYPE_MISMATCH -4
#define QUEUE_LIST_ERROR_SHARED -5
#define QUEUE_LIST_ERROR_MEMORY -6

#define QUEUE_TYPE_UNKNOWN 0
#define QUEUE_TYPE_INT 1
#define QUEUE_TYPE_DOUBLE 2
#define QUEUE_TYPE_CHAR 3
#define QUEUE_TYPE_FLOAT 4
#define QUEUE_TYPE_LONG 5
#define QUEUE_TYPE_POINTER 6

/**
 * @brief Node for linked list queue
 */
typedef struct QueueListNode {
    struct QueueListNode *next;
    char data[];
} QueueListNode;

/**
 * @brief Linked list queue container
 */
typedef struct QueueList {
    QueueListNode *head;
    QueueListNode *tail;
    size_t size;
    size_t elem_size;
    size_t capacity;
    bool fixed;
    int type_id;
    bool owns_nodes;
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_t lock;
#endif
} QueueList;

QueueList *queue_list_create(size_t elem_size, size_t capacity, bool fixed, int type_id);
void queue_list_destroy(QueueList *queue);
int queue_list_enqueue(QueueList *queue, const void *item, int item_type_id);
int queue_list_dequeue(QueueList *queue, void *out_item);
int queue_list_front(const QueueList *queue, void *out_item);
int queue_list_back(const QueueList *queue, void *out_item);
bool queue_list_is_empty(const QueueList *queue);
bool queue_list_is_full(const QueueList *queue);
size_t queue_list_size(const QueueList *queue);
size_t queue_list_capacity(const QueueList *queue);
void queue_list_clear(QueueList *queue);
int queue_list_get_type(const QueueList *queue);
QueueList *queue_list_clone_deep(const QueueList *source);
QueueList *queue_list_clone_shallow(const QueueList *source);
const char *queue_list_error_string(int code);

#define QUEUE_LIST_CREATE(type) queue_list_create(sizeof(type), 0, false, _QUEUE_LIST_TYPE_ID_FROM_TYPE(type))
#define QUEUE_LIST_CREATE_FIXED(type, capacity) queue_list_create(sizeof(type), (capacity), true, _QUEUE_LIST_TYPE_ID_FROM_TYPE(type))
#define QUEUE_LIST_ENQUEUE_INT(queue, value) do { \
    int temp = (value); \
    queue_list_enqueue((queue), &temp, QUEUE_TYPE_INT); \
} while (0)
#define QUEUE_LIST_ENQUEUE_DOUBLE(queue, value) do { \
    double temp = (value); \
    queue_list_enqueue((queue), &temp, QUEUE_TYPE_DOUBLE); \
} while (0)
#define QUEUE_LIST_ENQUEUE_CHAR(queue, value) do { \
    char temp = (value); \
    queue_list_enqueue((queue), &temp, QUEUE_TYPE_CHAR); \
} while (0)
#define QUEUE_LIST_ENQUEUE_FLOAT(queue, value) do { \
    float temp = (value); \
    queue_list_enqueue((queue), &temp, QUEUE_TYPE_FLOAT); \
} while (0)
#define QUEUE_LIST_ENQUEUE_LONG(queue, value) do { \
    long temp = (value); \
    queue_list_enqueue((queue), &temp, QUEUE_TYPE_LONG); \
} while (0)
#define QUEUE_LIST_FRONT(queue, type, out_var) do { \
    type temp; \
    if (queue_list_front((queue), &temp) == QUEUE_LIST_OK) { \
        *(out_var) = temp; \
    } \
} while (0)
#define QUEUE_LIST_BACK(queue, type, out_var) do { \
    type temp; \
    if (queue_list_back((queue), &temp) == QUEUE_LIST_OK) { \
        *(out_var) = temp; \
    } \
} while (0)

#define _QUEUE_LIST_TYPE_ID_FROM_TYPE(type) _Generic((type){0}, \
    int: QUEUE_TYPE_INT, \
    double: QUEUE_TYPE_DOUBLE, \
    char: QUEUE_TYPE_CHAR, \
    float: QUEUE_TYPE_FLOAT, \
    long: QUEUE_TYPE_LONG, \
    default: QUEUE_TYPE_POINTER \
)

#define _QUEUE_LIST_TYPE_ID_FROM_VALUE(expr) _Generic((expr), \
    int: QUEUE_TYPE_INT, \
    double: QUEUE_TYPE_DOUBLE, \
    char: QUEUE_TYPE_CHAR, \
    float: QUEUE_TYPE_FLOAT, \
    long: QUEUE_TYPE_LONG, \
    default: QUEUE_TYPE_POINTER \
)

#ifdef __cplusplus
}
#endif

#endif // QUEUE_LIST_H
