/**
 * @file queue_list.c
 * @brief Linked list queue implementation for generic data types
 * @author Generated by AI Assistant
 * @date 2026-05-13
 */

#include "queue_list.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#ifdef QUEUE_THREAD_SAFE
#include <pthread.h>
#define QUEUE_LIST_LOCK(queue) pthread_mutex_lock(&(queue)->lock)
#define QUEUE_LIST_UNLOCK(queue) pthread_mutex_unlock(&(queue)->lock)
#else
#define QUEUE_LIST_LOCK(queue) ((void)0)
#define QUEUE_LIST_UNLOCK(queue) ((void)0)
#endif

static QueueListNode *queue_list_node_create(size_t elem_size, const void *item)
{
    QueueListNode *node = (QueueListNode *)malloc(sizeof(QueueListNode) + elem_size);
    if (!node) {
        return NULL;
    }
    node->next = NULL;
    if (item) {
        memcpy(node->data, item, elem_size);
    }
    return node;
}

QueueList *queue_list_create(size_t elem_size, size_t capacity, bool fixed, int type_id)
{
    if (elem_size == 0) {
        return NULL;
    }

    if (fixed && capacity == 0) {
        return NULL;
    }

    QueueList *queue = (QueueList *)malloc(sizeof(QueueList));
    if (!queue) {
        return NULL;
    }

    queue->head = NULL;
    queue->tail = NULL;
    queue->size = 0;
    queue->elem_size = elem_size;
    queue->fixed = fixed;
    queue->capacity = fixed ? capacity : 0;
    queue->type_id = type_id;
    queue->owns_nodes = true;
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_init(&queue->lock, NULL);
#endif
    return queue;
}

void queue_list_destroy(QueueList *queue)
{
    if (!queue) {
        return;
    }

    if (queue->owns_nodes) {
        QueueListNode *current = queue->head;
        while (current) {
            QueueListNode *next = current->next;
            free(current);
            current = next;
        }
    }
#ifdef QUEUE_THREAD_SAFE
    if (queue->owns_nodes) {
        pthread_mutex_destroy(&queue->lock);
    }
#endif
    free(queue);
}

int queue_list_enqueue(QueueList *queue, const void *item, int item_type_id)
{
    if (!queue || !item) {
        return QUEUE_LIST_ERROR;
    }

    if (queue->type_id != QUEUE_TYPE_UNKNOWN && item_type_id != queue->type_id) {
        return QUEUE_LIST_ERROR_TYPE_MISMATCH;
    }

    if (!queue->owns_nodes) {
        return QUEUE_LIST_ERROR_SHARED;
    }

    if (queue->fixed && queue->size >= queue->capacity) {
        return QUEUE_LIST_ERROR_FULL;
    }

    QueueListNode *node = queue_list_node_create(queue->elem_size, item);
    if (!node) {
        return QUEUE_LIST_ERROR_MEMORY;
    }

    QUEUE_LIST_LOCK(queue);
    if (queue->tail) {
        queue->tail->next = node;
    } else {
        queue->head = node;
    }
    queue->tail = node;
    queue->size += 1;
    QUEUE_LIST_UNLOCK(queue);
    return QUEUE_LIST_OK;
}

int queue_list_dequeue(QueueList *queue, void *out_item)
{
    if (!queue || queue->size == 0) {
        return QUEUE_LIST_ERROR_EMPTY;
    }

    if (!queue->owns_nodes) {
        return QUEUE_LIST_ERROR_SHARED;
    }

    QUEUE_LIST_LOCK(queue);
    QueueListNode *node = queue->head;
    if (!node) {
        QUEUE_LIST_UNLOCK(queue);
        return QUEUE_LIST_ERROR_EMPTY;
    }

    if (out_item) {
        memcpy(out_item, node->data, queue->elem_size);
    }
    queue->head = node->next;
    if (!queue->head) {
        queue->tail = NULL;
    }
    queue->size -= 1;
    free(node);
    QUEUE_LIST_UNLOCK(queue);
    return QUEUE_LIST_OK;
}

int queue_list_front(const QueueList *queue, void *out_item)
{
    if (!queue || queue->size == 0 || !out_item) {
        return QUEUE_LIST_ERROR_EMPTY;
    }
    memcpy(out_item, queue->head->data, queue->elem_size);
    return QUEUE_LIST_OK;
}

int queue_list_back(const QueueList *queue, void *out_item)
{
    if (!queue || queue->size == 0 || !out_item) {
        return QUEUE_LIST_ERROR_EMPTY;
    }
    memcpy(out_item, queue->tail->data, queue->elem_size);
    return QUEUE_LIST_OK;
}

bool queue_list_is_empty(const QueueList *queue)
{
    return queue ? queue->size == 0 : true;
}

bool queue_list_is_full(const QueueList *queue)
{
    return queue ? (queue->fixed && queue->size >= queue->capacity) : false;
}

size_t queue_list_size(const QueueList *queue)
{
    return queue ? queue->size : 0;
}

size_t queue_list_capacity(const QueueList *queue)
{
    return queue ? queue->capacity : 0;
}

void queue_list_clear(QueueList *queue)
{
    if (!queue || !queue->owns_nodes) {
        return;
    }

    QUEUE_LIST_LOCK(queue);
    QueueListNode *current = queue->head;
    while (current) {
        QueueListNode *next = current->next;
        free(current);
        current = next;
    }
    queue->head = NULL;
    queue->tail = NULL;
    queue->size = 0;
    QUEUE_LIST_UNLOCK(queue);
}

int queue_list_get_type(const QueueList *queue)
{
    return queue ? queue->type_id : QUEUE_TYPE_UNKNOWN;
}

QueueList *queue_list_clone_deep(const QueueList *source)
{
    if (!source) {
        return NULL;
    }

    QueueList *copy = queue_list_create(source->elem_size, source->capacity, source->fixed, source->type_id);
    if (!copy) {
        return NULL;
    }

    QueueListNode *current = source->head;
    while (current) {
        int result = queue_list_enqueue(copy, current->data, source->type_id);
        if (result != QUEUE_LIST_OK) {
            queue_list_destroy(copy);
            return NULL;
        }
        current = current->next;
    }

    return copy;
}

QueueList *queue_list_clone_shallow(const QueueList *source)
{
    if (!source) {
        return NULL;
    }

    QueueList *copy = (QueueList *)malloc(sizeof(QueueList));
    if (!copy) {
        return NULL;
    }

    memcpy(copy, source, sizeof(QueueList));
    copy->owns_nodes = false;
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_init(&copy->lock, NULL);
#endif
    return copy;
}

const char *queue_list_error_string(int code)
{
    switch (code) {
        case QUEUE_LIST_OK:
            return "OK";
        case QUEUE_LIST_ERROR_EMPTY:
            return "Queue is empty";
        case QUEUE_LIST_ERROR_FULL:
            return "Queue is full";
        case QUEUE_LIST_ERROR_TYPE_MISMATCH:
            return "Type mismatch";
        case QUEUE_LIST_ERROR_SHARED:
            return "Shared shallow copy cannot be modified";
        case QUEUE_LIST_ERROR_MEMORY:
            return "Memory allocation failed";
        default:
            return "Unknown queue error";
    }
}
