/**
 * @file dynarray.h
 * @brief Dynamic array implementation header file
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This header provides a generic dynamic array implementation in C.
 * It supports storing elements of any type with automatic memory management.
 * Type-safe macros are provided for common operations.
 */

#ifndef DYNARRAY_H
#define DYNARRAY_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Type identifiers for runtime type checking
 */
#define DYNARRAY_TYPE_UNKNOWN 0
#define DYNARRAY_TYPE_INT 1
#define DYNARRAY_TYPE_DOUBLE 2
#define DYNARRAY_TYPE_CHAR 3
#define DYNARRAY_TYPE_FLOAT 4
#define DYNARRAY_TYPE_LONG 5
// Can be extended for more types

/**
 * @brief Dynamic array structure
 *
 * Contains metadata and data pointer for dynamic array management.
 */
typedef struct DynArray {
    void *data;        /**< Pointer to the array data */
    size_t size;       /**< Current number of elements */
    size_t capacity;   /**< Current allocated capacity */
    size_t elem_size;  /**< Size of each element in bytes */
    int type_id;       /**< Type identifier for type checking */
} DynArray;

/**
 * @brief Create a new dynamic array
 * @param elem_size Size of each element in bytes
 * @return Pointer to the new DynArray, or NULL on failure
 */
DynArray *dynarray_create(size_t elem_size);

/**
 * @brief Create a new dynamic array with initial capacity
 * @param elem_size Size of each element in bytes
 * @param capacity Initial capacity of the array
 * @return Pointer to the new DynArray, or NULL on failure
 */
DynArray *dynarray_create_with_capacity(size_t elem_size, size_t capacity);

/**
 * @brief Create a typed dynamic array
 * @param elem_size Size of each element in bytes
 * @param type_id Type identifier
 * @return Pointer to the new DynArray, or NULL on failure
 */
DynArray *dynarray_create_typed(size_t elem_size, int type_id);

/**
 * @brief Create a typed dynamic array with initial capacity
 * @param elem_size Size of each element in bytes
 * @param capacity Initial capacity of the array
 * @param type_id Type identifier
 * @return Pointer to the new DynArray, or NULL on failure
 */
DynArray *dynarray_create_with_capacity_typed(size_t elem_size, size_t capacity, int type_id);

/**
 * @brief Destroy a dynamic array and free its memory
 * @param arr Pointer to the DynArray to destroy
 */
void dynarray_destroy(DynArray *arr);

/**
 * @brief Reserve capacity for the array
 * @param arr Pointer to the DynArray
 * @param min_capacity Minimum capacity to reserve
 * @return 0 on success, -1 on failure
 */
int dynarray_reserve(DynArray *arr, size_t min_capacity);

/**
 * @brief Resize the array to a new size
 * @param arr Pointer to the DynArray
 * @param new_size New size of the array
 * @param default_value Default value for new elements (can be NULL)
 * @return 0 on success, -1 on failure
 */
int dynarray_resize(DynArray *arr, size_t new_size, const void *default_value);

/**
 * @brief Add an element to the end of the array
 * @param arr Pointer to the DynArray
 * @param item Pointer to the item to add
 * @return 0 on success, -1 on failure
 */
int dynarray_push_back(DynArray *arr, const void *item);

/**
 * @brief Remove the last element from the array
 * @param arr Pointer to the DynArray
 * @param out_item Pointer to store the removed item (can be NULL)
 * @return 0 on success, -1 on failure
 */
int dynarray_pop_back(DynArray *arr, void *out_item);

/**
 * @brief Get a pointer to an element at the specified index
 * @param arr Pointer to the DynArray
 * @param index Index of the element
 * @return Pointer to the element, or NULL if index is out of bounds
 */
void *dynarray_get(DynArray *arr, size_t index);

/**
 * @brief Get a const pointer to an element at the specified index
 * @param arr Pointer to the DynArray
 * @param index Index of the element
 * @return Const pointer to the element, or NULL if index is out of bounds
 */
const void *dynarray_const_get(const DynArray *arr, size_t index);

/**
 * @brief Set the value of an element at the specified index
 * @param arr Pointer to the DynArray
 * @param index Index of the element
 * @param item Pointer to the new value
 * @return 0 on success, -1 on failure
 */
int dynarray_set(DynArray *arr, size_t index, const void *item);

/**
 * @brief Clear all elements from the array (size becomes 0)
 * @param arr Pointer to the DynArray
 */
void dynarray_clear(DynArray *arr);

/**
 * @brief Get the current size of the array
 * @param arr Pointer to the DynArray
 * @return Current number of elements
 */
size_t dynarray_size(const DynArray *arr);

/**
 * @brief Get the current capacity of the array
 * @param arr Pointer to the DynArray
 * @return Current allocated capacity
 */
size_t dynarray_capacity(const DynArray *arr);

/**
 * @brief Get the type identifier of the array
 * @param arr Pointer to the DynArray
 * @return Type identifier
 */
int dynarray_get_type(const DynArray *arr);

/**
 * @brief Type-safe macros for dynamic array operations
 */
#define DYNARRAY_GET(arr, type, index) ((type *)dynarray_get(arr, index))
#define DYNARRAY_CONST_GET(arr, type, index) ((const type *)dynarray_const_get(arr, index))

// Type-safe creation and operation macros
#define DYNARRAY_CREATE(type) dynarray_create_typed(sizeof(type), _DYNARRAY_TYPE_ID(type))
#define DYNARRAY_CREATE_WITH_CAPACITY(type, capacity) dynarray_create_with_capacity_typed(sizeof(type), capacity, _DYNARRAY_TYPE_ID(type))
#define DYNARRAY_PUSH_BACK_INT(arr, value) do { \
    int temp = (value); \
    dynarray_push_back(arr, &temp); \
} while(0)
#define DYNARRAY_PUSH_BACK_DOUBLE(arr, value) do { \
    double temp = (value); \
    dynarray_push_back(arr, &temp); \
} while(0)
#define DYNARRAY_PUSH_BACK_CHAR(arr, value) do { \
    char temp = (value); \
    dynarray_push_back(arr, &temp); \
} while(0)
#define DYNARRAY_PUSH_BACK_FLOAT(arr, value) do { \
    float temp = (value); \
    dynarray_push_back(arr, &temp); \
} while(0)
#define DYNARRAY_PUSH_BACK_LONG(arr, value) do { \
    long temp = (value); \
    dynarray_push_back(arr, &temp); \
} while(0)
#define DYNARRAY_SET_INT(arr, index, value) do { \
    int temp = (value); \
    dynarray_set(arr, index, &temp); \
} while(0)
#define DYNARRAY_SET_DOUBLE(arr, index, value) do { \
    double temp = (value); \
    dynarray_set(arr, index, &temp); \
} while(0)
#define DYNARRAY_SET_CHAR(arr, index, value) do { \
    char temp = (value); \
    dynarray_set(arr, index, &temp); \
} while(0)
#define DYNARRAY_SET_FLOAT(arr, index, value) do { \
    float temp = (value); \
    dynarray_set(arr, index, &temp); \
} while(0)
#define DYNARRAY_SET_LONG(arr, index, value) do { \
    long temp = (value); \
    dynarray_set(arr, index, &temp); \
} while(0)
#define DYNARRAY_RESIZE_INT(arr, new_size, default_val) do { \
    int temp = (default_val); \
    dynarray_resize(arr, new_size, &temp); \
} while(0)
#define DYNARRAY_RESIZE_DOUBLE(arr, new_size, default_val) do { \
    double temp = (default_val); \
    dynarray_resize(arr, new_size, &temp); \
} while(0)
#define DYNARRAY_RESIZE_CHAR(arr, new_size, default_val) do { \
    char temp = (default_val); \
    dynarray_resize(arr, new_size, &temp); \
} while(0)
#define DYNARRAY_RESIZE_FLOAT(arr, new_size, default_val) do { \
    float temp = (default_val); \
    dynarray_resize(arr, new_size, &temp); \
} while(0)
#define DYNARRAY_RESIZE_LONG(arr, new_size, default_val) do { \
    long temp = (default_val); \
    dynarray_resize(arr, new_size, &temp); \
} while(0)

// Internal macro for type ID resolution
#define _DYNARRAY_TYPE_ID(type) _Generic((type){0}, \
    int: DYNARRAY_TYPE_INT, \
    double: DYNARRAY_TYPE_DOUBLE, \
    char: DYNARRAY_TYPE_CHAR, \
    float: DYNARRAY_TYPE_FLOAT, \
    long: DYNARRAY_TYPE_LONG, \
    default: DYNARRAY_TYPE_UNKNOWN \
)

DynArray *dynarray_create_typed(size_t elem_size, int type_id);
DynArray *dynarray_create_with_capacity_typed(size_t elem_size, size_t capacity, int type_id);

#define DYNARRAY_RESIZE(arr, new_size, default_val) do { \
    typeof(default_val) temp = (default_val); \
    dynarray_resize(arr, new_size, &temp); \
} while(0)

#ifdef __cplusplus
}
#endif

#endif // DYNARRAY_H
