/**
 * @file queue_array.h
 * @brief Circular queue implementation using an array buffer
 * @author Generated by AI Assistant
 * @date 2026-05-13
 *
 * This file provides a generic circular queue implementation with optional
 * fixed capacity, dynamic expansion, runtime type checking, deep and shallow
 * copy support, and clear error handling.
 *
 * Time complexity:
 *   enqueue: O(1) amortized for dynamic queue, O(1) for fixed queue
 *   dequeue: O(1)
 *   front/back: O(1)
 *   size/isEmpty/isFull/capacity: O(1)
 *   clear: O(n)
 *   clone_deep: O(n)
 *   clone_shallow: O(1)
 */

#ifndef QUEUE_ARRAY_H
#define QUEUE_ARRAY_H

#include <stdbool.h>
#include <stddef.h>

#ifdef QUEUE_THREAD_SAFE
#include <pthread.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Queue return codes
 */
#define QUEUE_ARRAY_OK 0
#define QUEUE_ARRAY_ERROR -1
#define QUEUE_ARRAY_ERROR_EMPTY -2
#define QUEUE_ARRAY_ERROR_FULL -3
#define QUEUE_ARRAY_ERROR_TYPE_MISMATCH -4
#define QUEUE_ARRAY_ERROR_SHARED -5
#define QUEUE_ARRAY_ERROR_MEMORY -6

/**
 * @brief Runtime type identifiers for queue elements
 */
#define QUEUE_TYPE_UNKNOWN 0
#define QUEUE_TYPE_INT 1
#define QUEUE_TYPE_DOUBLE 2
#define QUEUE_TYPE_CHAR 3
#define QUEUE_TYPE_FLOAT 4
#define QUEUE_TYPE_LONG 5
#define QUEUE_TYPE_POINTER 6

/**
 * @brief Circular queue structure backed by a resizable array
 */
typedef struct QueueArray {
    void *data;        /**< Pointer to underlying storage */
    size_t size;       /**< Number of stored elements */
    size_t capacity;   /**< Allocated capacity in elements */
    size_t elem_size;  /**< Element size in bytes */
    size_t head;       /**< Index of first element */
    size_t tail;       /**< Index after last element */
    int type_id;       /**< Runtime type identifier */
    bool dynamic;      /**< Whether the queue auto-expands */
    bool owns_data;    /**< Whether this instance owns the buffer */
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_t lock; /**< Optional mutex for thread safety */
#endif
} QueueArray;

/**
 * @brief Create a queue with optional fixed capacity
 * @param elem_size Size of each element in bytes
 * @param capacity Initial capacity to allocate
 * @param dynamic True for dynamic growth, false for fixed capacity
 * @param type_id Runtime type identifier
 * @return Pointer to a new queue, or NULL on allocation failure
 */
QueueArray *queue_array_create(size_t elem_size, size_t capacity, bool dynamic, int type_id);

/**
 * @brief Destroy a queue and free associated memory
 * @param queue Pointer to the queue
 */
void queue_array_destroy(QueueArray *queue);

/**
 * @brief Enqueue an element to the queue
 * @param queue Pointer to the queue
 * @param item Pointer to the element value
 * @param item_type_id Item runtime type identifier
 * @return QUEUE_ARRAY_OK on success, negative error code on failure
 */
int queue_array_enqueue(QueueArray *queue, const void *item, int item_type_id);

/**
 * @brief Dequeue the front element from the queue
 * @param queue Pointer to the queue
 * @param out_item Buffer to receive the dequeued element
 * @return QUEUE_ARRAY_OK on success, negative error code on failure
 */
int queue_array_dequeue(QueueArray *queue, void *out_item);

/**
 * @brief Access the front queue element without removing it
 * @param queue Pointer to the queue
 * @param out_item Buffer to receive the front element
 * @return QUEUE_ARRAY_OK on success, negative error code on failure
 */
int queue_array_front(const QueueArray *queue, void *out_item);

/**
 * @brief Access the back queue element without removing it
 * @param queue Pointer to the queue
 * @param out_item Buffer to receive the back element
 * @return QUEUE_ARRAY_OK on success, negative error code on failure
 */
int queue_array_back(const QueueArray *queue, void *out_item);

/**
 * @brief Check whether the queue is empty
 * @param queue Pointer to the queue
 * @return true if empty, false otherwise
 */
bool queue_array_is_empty(const QueueArray *queue);

/**
 * @brief Check whether the queue is full
 * @param queue Pointer to the queue
 * @return true if fixed capacity and size == capacity, false otherwise
 */
bool queue_array_is_full(const QueueArray *queue);

/**
 * @brief Get the current number of elements in the queue
 * @param queue Pointer to the queue
 * @return Current size
 */
size_t queue_array_size(const QueueArray *queue);

/**
 * @brief Get the current allocated capacity of the queue
 * @param queue Pointer to the queue
 * @return Current capacity
 */
size_t queue_array_capacity(const QueueArray *queue);

/**
 * @brief Clear all elements from the queue
 * @param queue Pointer to the queue
 */
void queue_array_clear(QueueArray *queue);

/**
 * @brief Get the runtime type identifier for the queue
 * @param queue Pointer to the queue
 * @return Type identifier
 */
int queue_array_get_type(const QueueArray *queue);

/**
 * @brief Create a deep copy of the queue
 *
 * The returned queue owns its own buffer and is independent of the source.
 * @param source Pointer to the source queue
 * @return New queue with copied elements, or NULL on failure
 */
QueueArray *queue_array_clone_deep(const QueueArray *source);

/**
 * @brief Create a shallow copy of the queue
 *
 * The returned queue shares the underlying buffer and cannot safely mutate it.
 * Use only for read-only inspection and do not destroy the source before the copy.
 * @param source Pointer to the source queue
 * @return New queue wrapper sharing the same buffer, or NULL on failure
 */
QueueArray *queue_array_clone_shallow(const QueueArray *source);

/**
 * @brief Convert an error code to a readable string
 * @param code Error code
 * @return Read-only string describing the error
 */
const char *queue_array_error_string(int code);

/**
 * @brief Create a dynamic queue for a given type
 */
#define QUEUE_ARRAY_CREATE(type) queue_array_create(sizeof(type), 4, true, _QUEUE_ARRAY_TYPE_ID_FROM_TYPE(type))

/**
 * @brief Create a fixed-capacity queue for a given type
 */
#define QUEUE_ARRAY_CREATE_FIXED(type, capacity) queue_array_create(sizeof(type), (capacity), false, _QUEUE_ARRAY_TYPE_ID_FROM_TYPE(type))

/**
 * @brief Enqueue a value with compile-time type inference
 */
#define QUEUE_ARRAY_ENQUEUE_INT(queue, value) do { \
    int temp = (value); \
    queue_array_enqueue((queue), &temp, QUEUE_TYPE_INT); \
} while (0)
#define QUEUE_ARRAY_ENQUEUE_DOUBLE(queue, value) do { \
    double temp = (value); \
    queue_array_enqueue((queue), &temp, QUEUE_TYPE_DOUBLE); \
} while (0)
#define QUEUE_ARRAY_ENQUEUE_CHAR(queue, value) do { \
    char temp = (value); \
    queue_array_enqueue((queue), &temp, QUEUE_TYPE_CHAR); \
} while (0)
#define QUEUE_ARRAY_ENQUEUE_FLOAT(queue, value) do { \
    float temp = (value); \
    queue_array_enqueue((queue), &temp, QUEUE_TYPE_FLOAT); \
} while (0)
#define QUEUE_ARRAY_ENQUEUE_LONG(queue, value) do { \
    long temp = (value); \
    queue_array_enqueue((queue), &temp, QUEUE_TYPE_LONG); \
} while (0)

/**
 * @brief Read the front element with compile-time type guidance
 */
#define QUEUE_ARRAY_FRONT(queue, type, out_var) do { \
    type temp; \
    if (queue_array_front((queue), &temp) == QUEUE_ARRAY_OK) { \
        *(out_var) = temp; \
    } \
} while (0)

/**
 * @brief Read the back element with compile-time type guidance
 */
#define QUEUE_ARRAY_BACK(queue, type, out_var) do { \
    type temp; \
    if (queue_array_back((queue), &temp) == QUEUE_ARRAY_OK) { \
        *(out_var) = temp; \
    } \
} while (0)

/**
 * @brief Internal macro to resolve the queue element type from a type name
 */
#define _QUEUE_ARRAY_TYPE_ID_FROM_TYPE(type) _Generic((type){0}, \
    int: QUEUE_TYPE_INT, \
    double: QUEUE_TYPE_DOUBLE, \
    char: QUEUE_TYPE_CHAR, \
    float: QUEUE_TYPE_FLOAT, \
    long: QUEUE_TYPE_LONG, \
    default: QUEUE_TYPE_POINTER \
)

/**
 * @brief Internal macro to resolve the queue element type from a value
 */
#define _QUEUE_ARRAY_TYPE_ID_FROM_VALUE(expr) _Generic((expr), \
    int: QUEUE_TYPE_INT, \
    double: QUEUE_TYPE_DOUBLE, \
    char: QUEUE_TYPE_CHAR, \
    float: QUEUE_TYPE_FLOAT, \
    long: QUEUE_TYPE_LONG, \
    default: QUEUE_TYPE_POINTER \
)

#ifdef __cplusplus
}
#endif

#endif // QUEUE_ARRAY_H
