/**
 * @file queue_array.c
 * @brief Circular queue implementation using an array buffer
 * @author Generated by AI Assistant
 * @date 2026-05-13
 */

#include "queue_array.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#ifdef QUEUE_THREAD_SAFE
#include <pthread.h>
#define QUEUE_ARRAY_LOCK(queue) pthread_mutex_lock(&(queue)->lock)
#define QUEUE_ARRAY_UNLOCK(queue) pthread_mutex_unlock(&(queue)->lock)
#else
#define QUEUE_ARRAY_LOCK(queue) ((void)0)
#define QUEUE_ARRAY_UNLOCK(queue) ((void)0)
#endif

static size_t queue_array_min_capacity(void)
{
    return 4;
}

static int queue_array_allocate(QueueArray *queue, size_t capacity)
{
    if (capacity == 0) {
        capacity = queue_array_min_capacity();
    }

    queue->data = malloc(capacity * queue->elem_size);
    if (!queue->data) {
        return QUEUE_ARRAY_ERROR_MEMORY;
    }

    queue->capacity = capacity;
    queue->head = 0;
    queue->tail = 0;
    return QUEUE_ARRAY_OK;
}

static int queue_array_grow(QueueArray *queue, size_t min_capacity)
{
    size_t new_capacity = queue->capacity ? queue->capacity * 2 : queue_array_min_capacity();
    if (new_capacity < min_capacity) {
        new_capacity = min_capacity;
    }

    void *new_data = malloc(new_capacity * queue->elem_size);
    if (!new_data) {
        return QUEUE_ARRAY_ERROR_MEMORY;
    }

    for (size_t i = 0; i < queue->size; ++i) {
        size_t index = (queue->head + i) % queue->capacity;
        memcpy((char *)new_data + i * queue->elem_size,
               (char *)queue->data + index * queue->elem_size,
               queue->elem_size);
    }

    free(queue->data);
    queue->data = new_data;
    queue->capacity = new_capacity;
    queue->head = 0;
    queue->tail = queue->size % queue->capacity;
    return QUEUE_ARRAY_OK;
}

static int queue_array_shrink(QueueArray *queue)
{
    if (!queue->dynamic || !queue->owns_data) {
        return QUEUE_ARRAY_OK;
    }

    size_t target_capacity = queue_array_min_capacity();
    if (queue->size > 0) {
        target_capacity = queue->size * 2;
    }
    if (target_capacity < queue_array_min_capacity()) {
        target_capacity = queue_array_min_capacity();
    }
    if (target_capacity >= queue->capacity) {
        return QUEUE_ARRAY_OK;
    }

    void *new_data = malloc(target_capacity * queue->elem_size);
    if (!new_data) {
        return QUEUE_ARRAY_ERROR_MEMORY;
    }

    for (size_t i = 0; i < queue->size; ++i) {
        size_t index = (queue->head + i) % queue->capacity;
        memcpy((char *)new_data + i * queue->elem_size,
               (char *)queue->data + index * queue->elem_size,
               queue->elem_size);
    }

    free(queue->data);
    queue->data = new_data;
    queue->capacity = target_capacity;
    queue->head = 0;
    queue->tail = queue->size % queue->capacity;
    return QUEUE_ARRAY_OK;
}

QueueArray *queue_array_create(size_t elem_size, size_t capacity, bool dynamic, int type_id)
{
    if (elem_size == 0) {
        return NULL;
    }

    QueueArray *queue = (QueueArray *)malloc(sizeof(QueueArray));
    if (!queue) {
        return NULL;
    }

    queue->elem_size = elem_size;
    queue->size = 0;
    queue->type_id = type_id;
    queue->dynamic = dynamic;
    queue->owns_data = true;
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_init(&queue->lock, NULL);
#endif

    if (queue_array_allocate(queue, capacity) != QUEUE_ARRAY_OK) {
#ifdef QUEUE_THREAD_SAFE
        pthread_mutex_destroy(&queue->lock);
#endif
        free(queue);
        return NULL;
    }

    return queue;
}

void queue_array_destroy(QueueArray *queue)
{
    if (!queue) {
        return;
    }

#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_lock(&queue->lock);
#endif
    if (queue->owns_data) {
        free(queue->data);
    }
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_unlock(&queue->lock);
    pthread_mutex_destroy(&queue->lock);
#endif
    free(queue);
}

int queue_array_enqueue(QueueArray *queue, const void *item, int item_type_id)
{
    if (!queue || !item) {
        return QUEUE_ARRAY_ERROR;
    }

    if (queue->type_id != QUEUE_TYPE_UNKNOWN && item_type_id != queue->type_id) {
        return QUEUE_ARRAY_ERROR_TYPE_MISMATCH;
    }

    if (!queue->owns_data) {
        return QUEUE_ARRAY_ERROR_SHARED;
    }

    QUEUE_ARRAY_LOCK(queue);
    if (queue->size >= queue->capacity) {
        if (!queue->dynamic) {
            QUEUE_ARRAY_UNLOCK(queue);
            return QUEUE_ARRAY_ERROR_FULL;
        }

        int result = queue_array_grow(queue, queue->size + 1);
        if (result != QUEUE_ARRAY_OK) {
            QUEUE_ARRAY_UNLOCK(queue);
            return result;
        }
    }

    memcpy((char *)queue->data + queue->tail * queue->elem_size, item, queue->elem_size);
    queue->tail = (queue->tail + 1) % queue->capacity;
    queue->size += 1;
    QUEUE_ARRAY_UNLOCK(queue);
    return QUEUE_ARRAY_OK;
}

int queue_array_dequeue(QueueArray *queue, void *out_item)
{
    if (!queue || queue->size == 0) {
        return QUEUE_ARRAY_ERROR_EMPTY;
    }

    if (!queue->owns_data) {
        return QUEUE_ARRAY_ERROR_SHARED;
    }

    QUEUE_ARRAY_LOCK(queue);
    if (out_item != NULL) {
        memcpy(out_item, (char *)queue->data + queue->head * queue->elem_size, queue->elem_size);
    }
    queue->head = (queue->head + 1) % queue->capacity;
    queue->size -= 1;

    if (queue->dynamic && queue->size < queue->capacity / 4) {
        queue_array_shrink(queue);
    }
    QUEUE_ARRAY_UNLOCK(queue);
    return QUEUE_ARRAY_OK;
}

int queue_array_front(const QueueArray *queue, void *out_item)
{
    if (!queue || queue->size == 0 || !out_item) {
        return QUEUE_ARRAY_ERROR_EMPTY;
    }
    memcpy(out_item, (char *)queue->data + queue->head * queue->elem_size, queue->elem_size);
    return QUEUE_ARRAY_OK;
}

int queue_array_back(const QueueArray *queue, void *out_item)
{
    if (!queue || queue->size == 0 || !out_item) {
        return QUEUE_ARRAY_ERROR_EMPTY;
    }
    size_t index = (queue->tail + queue->capacity - 1) % queue->capacity;
    memcpy(out_item, (char *)queue->data + index * queue->elem_size, queue->elem_size);
    return QUEUE_ARRAY_OK;
}

bool queue_array_is_empty(const QueueArray *queue)
{
    return queue ? queue->size == 0 : true;
}

bool queue_array_is_full(const QueueArray *queue)
{
    return queue ? (!queue->dynamic && queue->size >= queue->capacity) : false;
}

size_t queue_array_size(const QueueArray *queue)
{
    return queue ? queue->size : 0;
}

size_t queue_array_capacity(const QueueArray *queue)
{
    return queue ? queue->capacity : 0;
}

void queue_array_clear(QueueArray *queue)
{
    if (!queue) {
        return;
    }
    if (!queue->owns_data) {
        return;
    }

    QUEUE_ARRAY_LOCK(queue);
    queue->size = 0;
    queue->head = 0;
    queue->tail = 0;
    if (queue->dynamic && queue->capacity > queue_array_min_capacity()) {
        queue_array_shrink(queue);
    }
    QUEUE_ARRAY_UNLOCK(queue);
}

int queue_array_get_type(const QueueArray *queue)
{
    return queue ? queue->type_id : QUEUE_TYPE_UNKNOWN;
}

QueueArray *queue_array_clone_deep(const QueueArray *source)
{
    if (!source) {
        return NULL;
    }

    QueueArray *copy = queue_array_create(source->elem_size, source->capacity, source->dynamic, source->type_id);
    if (!copy) {
        return NULL;
    }

    for (size_t i = 0; i < source->size; ++i) {
        size_t index = (source->head + i) % source->capacity;
        memcpy((char *)copy->data + i * copy->elem_size,
               (char *)source->data + index * source->elem_size,
               source->elem_size);
    }
    copy->size = source->size;
    copy->head = 0;
    copy->tail = source->size % copy->capacity;
    return copy;
}

QueueArray *queue_array_clone_shallow(const QueueArray *source)
{
    if (!source) {
        return NULL;
    }

    QueueArray *copy = (QueueArray *)malloc(sizeof(QueueArray));
    if (!copy) {
        return NULL;
    }

    memcpy(copy, source, sizeof(QueueArray));
    copy->owns_data = false;
#ifdef QUEUE_THREAD_SAFE
    pthread_mutex_init(&copy->lock, NULL);
#endif
    return copy;
}

const char *queue_array_error_string(int code)
{
    switch (code) {
        case QUEUE_ARRAY_OK:
            return "OK";
        case QUEUE_ARRAY_ERROR_EMPTY:
            return "Queue is empty";
        case QUEUE_ARRAY_ERROR_FULL:
            return "Queue is full";
        case QUEUE_ARRAY_ERROR_TYPE_MISMATCH:
            return "Type mismatch";
        case QUEUE_ARRAY_ERROR_SHARED:
            return "Shared shallow copy cannot be modified";
        case QUEUE_ARRAY_ERROR_MEMORY:
            return "Memory allocation failed";
        default:
            return "Unknown queue error";
    }
}
