/**
 * @file stack.h
 * @brief Type-safe stack implementation header file
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This header provides a type-safe stack implementation in C.
 * The stack enforces type consistency at runtime to prevent type mismatches.
 * Automatic capacity management with expansion and contraction.
 */

#ifndef STACK_H
#define STACK_H

#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Type identifiers for runtime type checking
 */
#define STACK_TYPE_UNKNOWN 0
#define STACK_TYPE_INT 1
#define STACK_TYPE_DOUBLE 2
#define STACK_TYPE_CHAR 3
#define STACK_TYPE_FLOAT 4
// Can be extended for more types

/**
 * @brief Stack structure
 *
 * Contains metadata and data pointer for stack management with type safety.
 */
typedef struct Stack {
    void *data;        /**< Pointer to the stack data */
    size_t size;       /**< Current number of elements */
    size_t capacity;   /**< Current allocated capacity */
    size_t elem_size;  /**< Size of each element in bytes */
    int type_id;       /**< Type identifier for type checking */
} Stack;

/**
 * @brief Create a new stack with default capacity
 * @param elem_size Size of each element in bytes
 * @param type_id Type identifier
 * @return Pointer to the new Stack, or NULL on failure
 */
Stack *stack_create(size_t elem_size, int type_id);

/**
 * @brief Create a new stack with specified capacity
 * @param elem_size Size of each element in bytes
 * @param capacity Initial capacity of the stack
 * @param type_id Type identifier
 * @return Pointer to the new Stack, or NULL on failure
 */
Stack *stack_create_with_capacity(size_t elem_size, size_t capacity, int type_id);

/**
 * @brief Destroy a stack and free its memory
 * @param stack Pointer to the Stack to destroy
 */
void stack_destroy(Stack *stack);

/**
 * @brief Push an element onto the stack
 * @param stack Pointer to the Stack
 * @param item Pointer to the item to push
 * @param item_type_id Type ID of the item being pushed
 * @return 0 on success, -1 on failure (type mismatch or allocation error)
 */
int stack_push(Stack *stack, const void *item, int item_type_id);

/**
 * @brief Pop an element from the stack
 * @param stack Pointer to the Stack
 * @param out_item Pointer to store the popped item (can be NULL)
 * @return 0 on success, -1 on failure (empty stack)
 */
int stack_pop(Stack *stack, void *out_item);

/**
 * @brief Get the top element of the stack without removing it
 * @param stack Pointer to the Stack
 * @param out_item Pointer to store the top item
 * @return 0 on success, -1 on failure (empty stack)
 */
int stack_top(const Stack *stack, void *out_item);

/**
 * @brief Check if the stack is empty
 * @param stack Pointer to the Stack
 * @return true if empty, false otherwise
 */
bool stack_is_empty(const Stack *stack);

/**
 * @brief Get the current size of the stack
 * @param stack Pointer to the Stack
 * @return Current number of elements
 */
size_t stack_size(const Stack *stack);

/**
 * @brief Get the current capacity of the stack
 * @param stack Pointer to the Stack
 * @return Current allocated capacity
 */
size_t stack_capacity(const Stack *stack);

/**
 * @brief Get the type identifier of the stack
 * @param stack Pointer to the Stack
 * @return Type identifier
 */
int stack_get_type(const Stack *stack);

/**
 * @brief Clear all elements from the stack
 * @param stack Pointer to the Stack
 */
void stack_clear(Stack *stack);

/**
 * @brief Type-safe macros for stack operations
 */
#define STACK_CREATE(type) stack_create(sizeof(type), _STACK_TYPE_ID(type))
#define STACK_CREATE_WITH_CAPACITY(type, capacity) stack_create_with_capacity(sizeof(type), capacity, _STACK_TYPE_ID(type))

#define STACK_PUSH_INT(stack, value) do { \
    int temp = (value); \
    stack_push(stack, &temp, STACK_TYPE_INT); \
} while(0)
#define STACK_PUSH_DOUBLE(stack, value) do { \
    double temp = (value); \
    stack_push(stack, &temp, STACK_TYPE_DOUBLE); \
} while(0)
#define STACK_PUSH_CHAR(stack, value) do { \
    char temp = (value); \
    stack_push(stack, &temp, STACK_TYPE_CHAR); \
} while(0)
#define STACK_PUSH_FLOAT(stack, value) do { \
    float temp = (value); \
    stack_push(stack, &temp, STACK_TYPE_FLOAT); \
} while(0)
#define STACK_PUSH_LONG(stack, value) do { \
    long temp = (value); \
    stack_push(stack, &temp, STACK_TYPE_LONG); \
} while(0)

#define STACK_TOP(stack, type, out_var) do { \
    type temp; \
    if (stack_top(stack, &temp) == 0) { \
        *(out_var) = temp; \
    } \
} while(0)

// Internal macro for type ID resolution
#define _STACK_TYPE_ID(type) _Generic((type){0}, \
    int: STACK_TYPE_INT, \
    double: STACK_TYPE_DOUBLE, \
    char: STACK_TYPE_CHAR, \
    float: STACK_TYPE_FLOAT, \
    default: STACK_TYPE_UNKNOWN \
)

#ifdef __cplusplus
}
#endif

#endif // STACK_H