/**
 * @file stack.c
 * @brief Type-safe stack implementation source file
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This file contains the implementation of the type-safe stack functions.
 * It provides automatic memory management and runtime type checking.
 */

#include "stack.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>  // For error messages

/**
 * @brief Internal function to grow the stack capacity
 * @param stack Pointer to the Stack
 * @param min_capacity Minimum required capacity
 * @return 0 on success, -1 on failure
 */
static int stack_grow(Stack *stack, size_t min_capacity)
{
    size_t new_capacity = stack->capacity ? stack->capacity * 2 : 4;
    if (new_capacity < min_capacity) {
        new_capacity = min_capacity;
    }

    void *new_data = realloc(stack->data, new_capacity * stack->elem_size);
    if (!new_data) {
        return -1;
    }

    stack->data = new_data;
    stack->capacity = new_capacity;
    return 0;
}

/**
 * @brief Internal function to shrink the stack capacity
 * @param stack Pointer to the Stack
 * @param max_capacity Maximum allowed capacity
 * @return 0 on success, -1 on failure
 */
static int stack_shrink(Stack *stack, size_t max_capacity)
{
    if (stack->capacity <= 4) {
        return 0;  // Don't shrink below minimum capacity
    }

    size_t new_capacity = stack->capacity / 2;
    if (new_capacity < max_capacity) {
        new_capacity = max_capacity;
    }
    if (new_capacity < 4) {
        new_capacity = 4;
    }

    void *new_data = realloc(stack->data, new_capacity * stack->elem_size);
    if (!new_data) {
        return -1;
    }

    stack->data = new_data;
    stack->capacity = new_capacity;
    return 0;
}

Stack *stack_create(size_t elem_size, int type_id)
{
    return stack_create_with_capacity(elem_size, 0, type_id);
}

Stack *stack_create_with_capacity(size_t elem_size, size_t capacity, int type_id)
{
    if (elem_size == 0) {
        return NULL;
    }

    Stack *stack = (Stack *)malloc(sizeof(Stack));
    if (!stack) {
        return NULL;
    }

    stack->data = NULL;
    stack->size = 0;
    stack->capacity = 0;
    stack->elem_size = elem_size;
    stack->type_id = type_id;

    if (capacity > 0) {
        if (stack_grow(stack, capacity) != 0) {
            free(stack);
            return NULL;
        }
    }

    return stack;
}

void stack_destroy(Stack *stack)
{
    if (!stack) {
        return;
    }
    free(stack->data);
    free(stack);
}

int stack_push(Stack *stack, const void *item, int item_type_id)
{
    if (!stack || !item) {
        return -1;
    }

    // Type checking
    if (stack->type_id != STACK_TYPE_UNKNOWN && item_type_id != stack->type_id) {
        fprintf(stderr, "Error: Type mismatch in stack_push. Expected type %d, got %d\n",
                stack->type_id, item_type_id);
        return -1;
    }

    if (stack->size >= stack->capacity) {
        if (stack_grow(stack, stack->size + 1) != 0) {
            return -1;
        }
    }

    memcpy((char *)stack->data + stack->size * stack->elem_size, item, stack->elem_size);
    stack->size += 1;
    return 0;
}

int stack_pop(Stack *stack, void *out_item)
{
    if (!stack || stack->size == 0) {
        return -1;
    }
    stack->size -= 1;
    if (out_item != NULL) {
        memcpy(out_item, (char *)stack->data + stack->size * stack->elem_size, stack->elem_size);
    }

    // Shrink capacity if necessary (when size is much smaller than capacity)
    if (stack->size < stack->capacity / 4 && stack->capacity > 4) {
        stack_shrink(stack, stack->size * 2);
    }

    return 0;
}

int stack_top(const Stack *stack, void *out_item)
{
    if (!stack || stack->size == 0 || !out_item) {
        return -1;
    }
    memcpy(out_item, (char *)stack->data + (stack->size - 1) * stack->elem_size, stack->elem_size);
    return 0;
}

bool stack_is_empty(const Stack *stack)
{
    return stack ? stack->size == 0 : true;
}

size_t stack_size(const Stack *stack)
{
    return stack ? stack->size : 0;
}

size_t stack_capacity(const Stack *stack)
{
    return stack ? stack->capacity : 0;
}

int stack_get_type(const Stack *stack)
{
    return stack ? stack->type_id : STACK_TYPE_UNKNOWN;
}

void stack_clear(Stack *stack)
{
    if (!stack) {
        return;
    }
    stack->size = 0;
    // Optionally shrink capacity
    if (stack->capacity > 4) {
        stack_shrink(stack, 4);
    }
}