/**
 * @file main.c
 * @brief Main entry point for the C algorithm practice project
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This file contains the main function that runs all algorithm tests.
 * It serves as the entry point for the executable.
 */

#include <stdio.h>

/**
 * @brief Test function for two sum algorithm
 */
void test_two_sum();

/**
 * @brief Test function for basic sorting algorithms
 */
void test_basic_sort();

/**
 * @brief Test function for binary search algorithm
 */
void test_binary_search();

/**
 * @brief Test function for dynamic array implementation
 */
void test_dynarray();

/**
 * @brief Main entry point
 * @return 0 on success
 */
int main() {
    printf("=== C Algorithm Test ===\n");

    test_two_sum();
    test_basic_sort();
    test_binary_search();
    test_dynarray();
    
    return 0;
}