/**
 * @file main.c
 * @brief Main entry point for the C algorithm practice project
 * @author Generated by AI Assistant
 * @date 2026-05-09
 *
 * This file contains the main function that runs all algorithm tests.
 * It serves as the entry point for the executable.
 */

#include <stdio.h>

/**
 * @brief Test function for two sum algorithm
 */
void test_two_sum(void);

/**
 * @brief Test function for basic sorting algorithms
 */
void test_basic_sort(void);

/**
 * @brief Test function for binary search algorithm
 */
void test_binary_search(void);

/**
 * @brief Test function for dynamic array implementation
 */
void test_dynarray(void);

/**
 * @brief Test function for stack implementation
 */
void test_stack(void);
void test_queue(void);
void test_linked_list(void);
void test_tree(void);

/**
 * @brief Main entry point
 * @return 0 on success
 */
int main(void) {
    printf("=== C Algorithm Test ===\n");

    test_two_sum();
    test_basic_sort();
    test_binary_search();
    test_dynarray();
    test_stack();
    test_queue();
    test_linked_list();
    test_tree();
    
    return 0;
}